"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

import { disableKnowledgeSource, getKnowledgeChunks, getKnowledgeDocuments, getKnowledgeSource, getKnowledgeStatus, reindexKnowledgeSource } from "../lib/workspace";
import type { KnowledgeChunk, KnowledgeDocument, KnowledgeSource } from "../types/workspace";
import { useWorkspace } from "./workspace-provider";

export function KnowledgeSourceDetail({ companyId, sourceId }: { companyId: string; sourceId: string }) {
  const { organization } = useWorkspace(); const [source, setSource] = useState<KnowledgeSource | null>(null); const [documents, setDocuments] = useState<KnowledgeDocument[]>([]); const [chunks, setChunks] = useState<Record<string, KnowledgeChunk[]>>({}); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!organization) return; try { const [item, docs] = await Promise.all([getKnowledgeSource(organization.id, companyId, sourceId), getKnowledgeDocuments(organization.id, companyId, sourceId)]); setSource(item); setDocuments(docs.items); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load source."); } }, [organization, companyId, sourceId]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (!organization || source?.status !== "processing") return; const id = window.setInterval(() => { getKnowledgeStatus(organization.id, companyId, sourceId).then((result) => setSource(result.source)).catch(() => undefined); }, 3000); return () => window.clearInterval(id); }, [organization, companyId, sourceId, source?.status]);
  async function action(operation: () => Promise<KnowledgeSource>) { setBusy(true); setError(null); try { setSource(await operation()); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Operation failed."); } finally { setBusy(false); } }
  async function showChunks(documentId: string) { if (!organization) return; try { const result = await getKnowledgeChunks(organization.id, companyId, documentId); setChunks((current) => ({ ...current, [documentId]: result.items })); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load chunks."); } }
  if (!organization || !source) return <section className="content-section"><div className="page-state">{error || "Loading source…"}</div></section>;
  return <section className="content-section"><Link className="back-link" href={`/dashboard/companies/${companyId}/knowledge`}>← Knowledge</Link><div className="content-header"><div><div className="eyebrow">{source.type} source</div><h1>{source.name}</h1><p className="content-subtitle">{source.source_url || "Private source"}</p></div><span className={`source-status source-${source.status}`}>{source.status}</span></div><div className="source-detail-grid"><div><span>Documents</span><strong>{source.documents_count}</strong></div><div><span>Chunks</span><strong>{source.chunks_count}</strong></div><div><span>Last indexed</span><strong>{source.last_indexed_at ? new Date(source.last_indexed_at).toLocaleString() : "—"}</strong></div></div>{source.last_error && <p className="form-error" role="alert">{source.last_error}</p>}<div className="detail-actions">{source.status !== "disabled" && <button className="primary-button" disabled={busy || source.status === "processing"} onClick={() => void action(() => reindexKnowledgeSource(organization.id, companyId, sourceId))}>Reindex</button>}{source.status !== "disabled" && <button className="secondary-button" disabled={busy || source.status === "processing"} onClick={() => void action(() => disableKnowledgeSource(organization.id, companyId, sourceId))}>Disable source</button>}</div><div className="document-preview"><h2>Documents</h2>{documents.length === 0 && <p className="content-subtitle">No active documents yet.</p>}{documents.map((document) => <article className="document-card" key={document.id}><div className="document-heading"><h3>{document.title}</h3><button className="text-button" type="button" onClick={() => void showChunks(document.id)}>{chunks[document.id] ? "Hide chunks" : "Preview chunks"}</button></div><p className="document-source">{document.source_url || document.content_type} · {document.content_hash.slice(0, 12)}</p><pre>{document.content}</pre>{chunks[document.id] && <div className="chunk-list">{chunks[document.id].map((chunk) => <div className="chunk-card" key={chunk.id}><strong>Chunk {chunk.chunk_index + 1} · ~{chunk.approx_token_count ?? "?"} tokens</strong><p>{chunk.content}</p></div>)}</div>}</article>)}</div></section>;
}
